name: Update Leaderboard
on:
  push:
    branches: [ main ]
    paths:
      - 'results/**.json'
  workflow_dispatch:
jobs:
  leaderboard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install -r requirements.txt
      - name: Generate leaderboard
        run: python scripts/generate_leaderboard.py
      - name: Publish html/ to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
